#!/usr/bin/env bash

### Configurations and settings ###

# Colors
source $DOTFILES/helpers/colors
# Error function
source $DOTFILES/helpers/check_errors.sh

sudo true
## Lets get started
printf "\n${BLUE}${UNDERLINE}Configurations${NC}\n\n"

printf "\n${GREEN}${UNDERLINE}General:${NC}\n"
## iTerm
printf "${BLUE}Setting iTerm settings${NC}\n"
./.iterm2; check_errs $?
printf "\033[1A\r\033[0K${GREEN}iTerm settings\t\t✔${NC}\n"

## MacOS
printf "${BLUE}Setting macOS settings${NC}\n"
./.macos; check_errs $?
printf "\033[1A\r\033[0K${GREEN}macOS settings\t\t✔${NC}\n"

## Zsh config
### Remove zshrc if it exists, and symlink this in
printf "${BLUE}Replacing zsh config${NC}\n"
rm -rf $HOME/.zshrc; check_errs $?
ln -s $DOTFILES/.zshrc $HOME/.zshrc; check_errs $?
printf "\033[1A\r\033[0K${GREEN}zsh config\t\t✔${NC}\n"

## git
printf "\n${GREEN}${UNDERLINE}git:${NC}\n"
# Replace .gitconfig with symlink here
printf "${BLUE}Replacing global .gitconfig${NC}\n"
rm -rf $HOME/.gitconfig; check_errs $?
ln -s $DOTFILES/git/.gitconfig $HOME/.gitconfig; check_errs $?
printf "\033[1A\r\033[0K${GREEN}Global gitconfig\t✔${NC}\n"

printf "${BLUE}Replacing global .gitignore${NC}\n"
# Replace .gitignore with symlink here
rm -rf $HOME/.gitignore; check_errs $?
ln -s $DOTFILES/git/.gitignore $HOME/.gitignore; check_errs $?
printf "\033[1A\r\033[0K${GREEN}Global gitignore\t✔${NC}\n"

# VSCode
printf "\n${GREEN}${UNDERLINE}Visual Studio Code:${NC}\n"
# If the folder doesn't exist we create it
printf "${BLUE}  Ensuring vscode config folder is made.${NC}\n"
mkdir -p ~/Library/Application\ Support/Code/User/; check_errs $?
printf "\033[1A\r\033[0K${GREEN}  Config folder\t✔${NC}\n"
## Settings
printf "${BLUE}  Settings${NC}\n"
ln -sf $DOTFILES/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json; check_errs $?
printf "\033[1A\r\033[0K${GREEN}  Settings\t✔${NC}\n"
## Bindings
printf "${BLUE}  Keybindings${NC}\n"
ln -sf $DOTFILES/vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json; check_errs $?
printf "\033[1A\r\033[0K${GREEN}  Keybindings\t✔${NC}\n"
## Snippets
printf "${BLUE}  Snippets${NC}\n"
ln -sf $DOTFILES/vscode/snippets/ ~/Library/Application\ Support/Code/User; check_errs $?
printf "\033[1A\r\033[0K${GREEN}  Snippets\t✔${NC}\n"

printf "\n${BLUE}${UNDERLINE}Installing vscode extensions through code-extensions${NC}\n"
## Extensions
./vscode/bin/code-extensions install --filename ./vscode/extensions; check_errs $?
printf "\033[1A\033[1A\033[1A\033[1A\033[1A\033[1A\033[1A\r\033[0K${GREEN}  Extensions\t✔${NC}\n"