#!/usr/bin/env bash

### Basic installation of the dotfiles ###

export DOTFILES=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

# Colors
source $DOTFILES/helpers/colors
# Error function
source $DOTFILES/helpers/check_errors.sh

printf "\n${BLUE}Full installation of dotfiles starting now. 🤖${NC}\n\n"


# Get sudo from user for this session, just in case
sudo true

# Install brew if it is not installed
if test ! $(which brew); then
  printf "${BLUE}Installing brew${NC}\n"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /dev/null
  check_errs $?
fi

printf "${BLUE}Updating & Upgrading brew. This might take a while..${NC}\n"
brew update > /dev/null; check_errs $?
brew upgrade > /dev/null; check_errs $?
brew tap homebrew/bundle > /dev/null; check_errs $?

printf "${BLUE}Installing from Brewfile..${NC}\n"
brew bundle; check_errs $?

./config