#!/usr/bin/env bash

### Setup the execution of the script ### 

# Clone the git repository
git clone git@github.com:jonjohansen/dotfiles-macos.git ~/.dotfiles-macos

cd .dotfiles-macos
./installation.sh
