

[line_break]
disabled = true

[character] 
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[username]
show_always = true
format = "[$user]($style):"
style_user = "bold blue"

[hostname]
ssh_only = false
style = "bold blue"

[nodejs]
style = "bold green"

